OrdererOrgs:
  - Name: Orderer
    Domain: automobile-registration-network.com
    Specs:
      - Hostname: orderer
PeerOrgs:
 - Name: partsFactory
   Domain: partsFactory.automobile-registration-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: carFactory
   Domain: carFactory.automobile-registration-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: dealer
   Domain: dealer.automobile-registration-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
